spring:
  datasource:
    url: jdbc:mysql://localhost/order_mgmt
    username: root
    password: tmdgks1817@
  thymeleaf:
    view-names: "views/*"
    prefix: "/WEB-INF/"
server:
  servlet:
    context-path: /kdt
