spring:
  application:
    name: spring security 10
  messages:
    basename: i18n/messages
    encoding: UTF-8
    cache-duration: PT1H
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    database: h2
    open-in-view: false
    show-sql: false
    hibernate:
      ddl-auto: none
      use-new-id-generator-mappings: false
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate.dialect: org.hibernate.dialect.H2Dialect
  datasource:
    driver-class-name: org.h2.Driver
    url: "jdbc:h2:mem:spring_security;MODE=MYSQL;DB_CLOSE_DELAY=-1"
    username: sa
    password:
    hikari:
      minimum-idle: 1
      maximum-pool-size: 5
      pool-name: H2_DB
  sql:
    init:
      platform: h2
      schema-locations: classpath:sql/schema_new.sql, classpath:org/springframework/security/oauth2/client/oauth2-client-schema.sql
      data-locations: classpath:sql/data_new.sql
      encoding: UTF-8
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-name: kakao
            client-id: 417c346a5ac77e235b0ce3a98122fdbc #Rest API 키
            client-secret: RIqSv3xvxwD7HauYeZHirbSMdtua5xSr # 보안 - client secret key
            scope: profile_nickname, profile_image # 필수 동의 항목들
            redirect-uri: "http://localhost:8080/login/oauth2/code/{registrationId}" # 아래에 kakao만 등록하면 마지막에 kakao가 들어감
            authorization-grant-type: authorization_code
            client-authentication-method: POST
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize # 1회성 승인 코드를 받기 위한 URI
            token-uri: https://kauth.kakao.com/oauth/token # access token을 발급 받기 위한 api
            user-info-uri: https://kapi.kakao.com/v2/user/me # access token을 이용 사용자 정보를 가져오기 위한 API
            user-name-attribute: id # api 에서 사용자 식별 정보를 가져왔을 때 식별할 수 있는 고유 식별 키?
server:
  port: 8080
jwt:
  header: token
  issuer: prgrms
  client-secret: EENY5W0eegTf1naQB2eDeyCLl5kRS2b8xa5c4qLdS0hmVjtbvo8tOyhPMcAmtPuQ
  expiry-seconds: 60
